apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-secret
  namespace: appdynamics
type: Opaque
stringData:
  controller-key: ACCESS_KEY
  api-user: CONTROLLER_USERNAME@CONTROLLER_ACCOUNT:CONTROLLER_PASSWORD