apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-infraviz
  namespace: appdynamics
---
apiVersion: cluster.appdynamics.com/v1alpha1
kind: InfraViz
metadata:
  name: appdynamics-infraviz
  namespace: appdynamics
spec:
  controllerUrl: "https://CONTROLLER_ACCOUNT.saas.appdynamics.com:443"
  image: "docker.io/appdynamics/machine-agent:22.7.0"
  # imagePullSecret: "regcred"
  account: "CONTROLLER_ACCOUNT"
  globalAccount: "GLOBAL_ACCOUNT_NAME"
  enableContainerHostId: true
  enableServerViz: true
  netVizImage: "appdynamics/machine-agent-netviz:21.3.0"
  netVizPort: 3892
  enableMasters: true

