apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "SESSION"
spec:
  defaultBackend:
    service:
      name: angular-frontend
      port:
        number: 80
# in a future versionof k8s (1.22?) this will be required and the kubernetes.io/ingress.class will be deprecated
#  ingressClassName: nginx  
  rules:
  -  http:
      paths:
      - path: /ecommerce
        pathType: Prefix
        backend:
          service:
            name: ecommerce-svc 
            port:
              number: 8080