apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecom-logistics-svc
  labels:
    app: ecom-logistics-svc
    framework: java
    appd-appname: AD-Ecommerce-AI
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cmap-controller.yaml") . | sha256sum }}
spec:
  serviceName: ecom-logistics-svc
  replicas: 1
  selector:
    matchLabels:
      app: ecom-logistics-svc
  template:
    metadata:
      labels:
        app: ecom-logistics-svc
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
      - name: logistics-svc
        image: {{ .Values.docker_repo }}/ad-ecommerce-java-services-noin:{{ .Values.app_tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: logistics-svc
        resources:
          limits:
            cpu: "800m"
            memory: 2Gi
          requests:
            cpu: "250m"
            memory: 250Mi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        envFrom:
          - configMapRef:
              name: application-config
          - configMapRef:
              name: controller-config
        env:
          - name: DISABLE_THREAD_DELAY
            value: "true"
          - name: DISABLE_QUERY_DELAY
            value: "true"
          - name: DEMO_RELEASE_TYPE
            value: green
          - name: DEMO_RELEASE_VERSION
            value: 1.1.3
          - name: ALWAYS_ADD_MEMORY
            value: "yes"
          - name: MIN_PCT_FREE_MEM
            value: "7"
          - name: MEM_INCREMENT_MB
            value: "1"
          - name: PAUSE_PER_LOOP_MS
            value: "400"
          - name: PCT_TRANSFER_TO_HARD_REF
            value: "5"
          - name: MIN_LIST_SIZE_TO_TRANSFER
            value: "27"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://mysqldb:3306/ecommerce
          - name: SPRING_REDIS_HOST
            value: redisdb
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 900
          periodSeconds: 60
          timeoutSeconds: 5
        volumeMounts:
          - mountPath: /appagent
            name: shared-files
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: logistics-svc
  name: logistics-svc
spec:
  clusterIP: 10.97.157.34
  ports:
  - port: 8080
  selector:
    app: ecom-logistics-svc
