apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecom-order-processing
  labels:
    app: ecom-order-processing
    framework: dotnetcore
    appd-appname: AD-Ecommerce-AI
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cmap-controller.yaml") . | sha256sum }}
spec:
  serviceName: ecom-order-processing
  replicas: 1
  selector:
    matchLabels:
      app: ecom-order-processing
  template:
    metadata:
      labels:
        app: ecom-order-processing
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
      - name: order-processing
        image: {{ .Values.docker_repo }}/ad-ecommerce-dotnet-services:{{ .Values.app_tag }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "800m"
            memory: 2Gi
          requests:
            cpu: "250m"
            memory: 250Mi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        envFrom:
          - configMapRef:
              name: controller-config
        env:
          - name: GENERATE_ERRORS 
            value: "true"
          - name: SLOW_RESPONSE_TIME_START 
            value: "45"
          - name: SLOW_RESPONSE_TIME_END 
            value: "60"
          - name: DELAY_DURATION 
            value: "2000"                                    
        volumeMounts:
          - mountPath: /sharedFiles
            name: shared-files
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: order-processing
 name: order-processing
spec:
 clusterIP: 10.97.157.33
 ports:
 - port: 8080
 selector:
   app: ecom-order-processing
