apiVersion: cluster.appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "edu-cluster"
  controllerUrl: "https://9i9t.saas.appdynamics.com:443"
  account: "9i9t"
  image: "docker.io/appdynamics/cluster-agent:22.7.0"
  serviceAccountName: appdynamics-cluster-agent
  nsToMonitorRegex: ".*"
  stdoutLogging: "true"
  instrumentationMethod: Env
  resourcesToInstrument:
    - Deployment
    - StatefulSet
  nsToInstrumentRegex: ai-*
  defaultAnalyticsHost: appdynamics-infraviz.appdynamics.svc.cluster.local
  defaultAnalyticsPort: 9090
  defaultAnalyticsSslEnabled: false
  defaultAppName: AI-App
  appNameStrategy: manual
  imageInfo:
      java:
        image: "docker.io/appdynamics/java-agent:22.7.0"
        agentMountPath: /opt/appdynamics
        imagePullPolicy: IfNotPresent
      dotnetcore:
        image: "docker.io/appdynamics/dotnet-core-agent:22.7.0"
        agentMountPath: /opt/appdynamics
        imagePullPolicy: IfNotPresent
      nodejs:
        image: "docker.io/appdynamics/nodejs-agent:21.9.0-16-alpine"
        agentMountPath: /opt/appdynamics
        imagePullPolicy: IfNotPresent
  instrumentationRules:
    - namespaceRegex: ai-ecom
      language: java
      labelMatch:
        - framework: java
      appName: AD-Ecommerce-AI
    - namespaceRegex: ai-ecom
      language: dotnetcore
      labelMatch:
        - framework: dotnetcore
      appName: AD-Ecommerce-AI
    - namespaceRegex: ai-java
      language: java
      appName: ai-java
    - namespaceRegex: ai-dotnet
      language: dotnetcore
      appName: ai-dotnet
    - namespaceRegex: ai-node
      language: nodejs
      appName: ai-node
