apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecom-cron-acct
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ecom-cron-acct
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ecom-cron-acct
subjects:
- kind: ServiceAccount
  name: ecom-cron-acct
  namespace: {{ .Release.Namespace | quote }}  
roleRef:
  kind: Role
  name: ecom-cron-acct
  apiGroup: rbac.authorization.k8s.io