apiVersion: v1
data:
   JAVA_SERVICES_INVENTORY_URL: http://inventory-svc:8080
   JAVA_SERVICES_LOGISTICS_URL: http://logistics-svc:8080
   API_MAIN_SUPPLIER_URL: http://api-main-supplier:8081
   API_SECONDARY_SUPPLIER_URL: http://api-secondary-supplier:8081
   API_LOGISTICS_URL: http://api-logistics:8081
   SPRING_RABBITMQ_HOST: rabbitmq
kind: ConfigMap
metadata:
  name: application-config
