apiVersion: v1
data:
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: {{ .Values.account_access_key | quote }}
  APPDYNAMICS_AGENT_ACCOUNT_NAME: {{ .Values.account_name | quote }}
  APPDYNAMICS_AGENT_APPLICATION_NAME: {{ .Values.application_name }}
  APPDYNAMICS_CONTROLLER_HOST_NAME: {{ .Values.controller_host | quote }}
  APPDYNAMICS_CONTROLLER_PORT: {{ .Values.controller_port | quote }}
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: {{ .Values.controller_ssl_enabled | quote }}
  APPDYNAMICS_NETVIZ_AGENT_PORT: "3892"
  NODEJS_AGENT_VERSION: {{ .Values.nodejs_agent_version | quote }}
kind: ConfigMap
metadata:
  name: controller-config
