apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecom-order-processing
  labels:
    app: ecom-order-processing
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/cmap-controller.yaml") . | sha256sum }}
spec:
  serviceName: ecom-order-processing
  replicas: 1
  selector:
    matchLabels:
      app: ecom-order-processing
  template:
    metadata:
      labels:
        app: ecom-order-processing
    spec:
#      imagePullSecrets:
#          - name: regcred
      initContainers:
      - name: agent-repo
        image: {{ .Values.appd_repo }}/dotnet-core-agent:{{ .Values.agent_tag }}
        command: ["cp", "-ra", "/opt/appdynamics/.", "/mountPath"]
        volumeMounts:
        - mountPath: /mountPath
          name: shared-files
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
      - name: order-processing
        image: {{ .Values.docker_repo }}/ad-ecommerce-dotnet-services:{{ .Values.app_tag }}
#        command: ["sleep", "10000"]
        imagePullPolicy: IfNotPresent
#        ports:
#        - containerPort: 8080
#          name: order-processing
        resources:
          limits:
            cpu: "800m"
            memory: 2Gi
          requests:
            cpu: "250m"
            memory: 250Mi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        envFrom:
          - configMapRef:
              name: controller-config
        env:
          - name: APPDYNAMICS_AGENT_TIER_NAME
            value: Order-Processing-Services
          - name: APPDYNAMICS_AGENT_NODE_NAME
            value: Ecommerce_MS_NODE
          - name: CORECLR_PROFILER
            value: "{57e1aa68-2229-41aa-9931-a6e93bbc64d8}"
          - name: CORECLR_ENABLE_PROFILING 
            value: "1"
          - name: CORECLR_PROFILER_PATH 
            value: /sharedFiles/libappdprofiler.so
          - name: GENERATE_ERRORS 
            value: "true"
          - name: SLOW_RESPONSE_TIME_START 
            value: "45"
          - name: SLOW_RESPONSE_TIME_END 
            value: "60"
          - name: DELAY_DURATION 
            value: "2000"                              
#        livenessProbe:
#          tcpSocket:
#            port: 8080
#          initialDelaySeconds: 300
#          periodSeconds: 60
        volumeMounts:
          - mountPath: /sharedFiles
            name: shared-files
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: order-processing
 name: order-processing
spec:
 clusterIP: 10.96.157.33
 ports:
 - port: 8080
 selector:
   app: ecom-order-processing
