apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ecom-redisdb
  labels:
    app: ecom-redisdb
spec:
  serviceName: ecom-redisdb
  replicas: 1
  selector:
    matchLabels:
      app: ecom-redisdb
  template:
    metadata:
      labels:
        app: ecom-redisdb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: redisdb
          image: bitnami/redis:7.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redisdb
          resources:
            limits:
              cpu: 800m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 250Mi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          env:
            - name: REDIS_PASSWORD
              value: redis123
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 300
            periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redisdb
  name: redisdb
spec:
  clusterIP: 10.96.157.50
  ports:
    - port: 6379
  selector:
    app: ecom-redisdb
