apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-res-limits
  namespace: ecom
spec:
  selector:
    matchLabels:
      app: redis-rlimits
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-rlimits
    spec:
      containers:
      - name: redis-rlimits
        image: redis
        resources:
          limits: 
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
