apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment-random-exit
  namespace: ecom
spec:
  selector:
    matchLabels:
      app: redis-deployment-random-exit
  replicas: 9
  template:
    metadata:
      labels:
        app: redis-deployment-random-exit
    spec:
      containers:
      - name: redis-deployment-random-exit
        image: redis
        command: ["/bin/bash","-c","--"]
        args: ["sleep $((120 + $RANDOM % 300)); exit 1"]
        imagePullPolicy: IfNotPresent
        resources:
          limits: 
            cpu: 50m
            memory: 100M
          requests:
            cpu: 20m
            memory: 50M
        ports:
        - containerPort: 6379